src/com/report/model/ReportService.java
package com.report.model;

import java.util.List;

public class ReportService {
	
	
	private Report_interface dao;

	public ReportService() {		
		dao = new ReportDAO();
	}
	
	public List<ReportVO> getAll(){
		return dao.getAll();
	}
	
	
}

src/com/report/model/ReportVO.java
package com.report.model;

public class ReportVO {
	
	private	Integer REPORT_NO; 
	private 	String REPORT; 
	private 	String REPORT_MSG; 
	private 	String REPORT_STATUS; 
	private 	String MANAGER_NO; 
	
	@Override
	public String toString() {
		return "ReportVO [REPORT_NO=" + REPORT_NO + ", REPORT=" + REPORT + ", REPORT_MSG=" + REPORT_MSG
				+ ", REPORT_STATUS=" + REPORT_STATUS + ", MANAGER_NO=" + MANAGER_NO + "]";
	}
	public Integer getREPORT_NO() {
		return REPORT_NO;
	}
	public void setREPORT_NO(Integer rEPORT_NO) {
		this.REPORT_NO = rEPORT_NO;
	}
	public String getREPORT() {
		return REPORT;
	}
	public void setREPORT(String rEPORT) {
		this.REPORT = rEPORT;
	}
	public String getREPORT_MSG() {
		return REPORT_MSG;
	}
	public void setREPORT_MSG(String rEPORT_MSG) {
		this.REPORT_MSG = rEPORT_MSG;
	}
	public String getREPORT_STATUS() {
		return REPORT_STATUS;
	}
	public void setREPORT_STATUS(String rEPORT_STATUS) {
		this.REPORT_STATUS = rEPORT_STATUS;
	}
	public String getMANAGER_NO() {
		return MANAGER_NO;
	}
	public void setMANAGER_NO(String mANAGER_NO) {
		this.MANAGER_NO = mANAGER_NO;
	}
	
	
	
}

src/com/report/model/Report_interface.java
package com.report.model;

import java.util.List;

public interface Report_interface {
	
	public void insert(ReportVO reportVO);
	public void update(ReportVO reportVO);
	public void delete(Integer REPORT_NO);
	public ReportVO findPrimaryKey(Integer REPORT_NO);
	public List<ReportVO> getAll();
	
}

WebContent/backstage/event_management.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<%@ page import="com.manager.model.*"%>
<%@ page import="java.util.*"%>
<%@ page import="java.text.*"%>
<%@ page import="java.util.stream.Collectors"%>
<%@ page import="com.activity.model.*"%>

<%
	if (session.getAttribute("manager") == null) {
		RequestDispatcher dispatcher = request.getRequestDispatcher("/backstage/login.jsp");
		dispatcher.forward(request, response);
	}

	ActivityService activitySvc = new ActivityService();
	List<ActivityVO> list = activitySvc.getAll();

	List<ActivityVO> listA0 = list.stream().filter(e -> e.getStatus().equals("a0"))
			.collect(Collectors.toList());

	List<ActivityVO> listA1 = list.stream().filter(e -> e.getStatus().equals("a1"))
			.collect(Collectors.toList());

	List<ActivityVO> listA2 = list.stream().filter(e -> e.getStatus().equals("a2"))
			.collect(Collectors.toList());

	List<ActivityVO> listA3 = list.stream().filter(e -> e.getStatus().equals("a3"))
			.collect(Collectors.toList());

	pageContext.setAttribute("listA0", listA0);
	pageContext.setAttribute("listA1", listA1);
	pageContext.setAttribute("listA2", listA2);
	pageContext.setAttribute("listA3", listA3);
%>

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<link
	href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap"
	rel="stylesheet">
<link rel="stylesheet"
	href="<%=request.getContextPath()%>/css/backstage-css/basic.css" />
<link rel="stylesheet"
	href="<%=request.getContextPath()%>/css/backstage-css/backendmanagercheack1.css">
<title>活動管理</title>


</head>
<body>
	<div class="block1"></div>
	<div class="bg">
		<img src="<%=request.getContextPath()%>/img/backstage-img/bg.png"
			alt="">
	</div>
	<div class="main">
		<div class="main-div">
			<div class="panel-div">

				<div class="name">
					<img src="<%=request.getContextPath()%>/PicReader" alt="" />
					<p>${manager.nickname}</p>
				</div>



				<div class="homepage">
					<a href="<%=request.getContextPath()%>/backstage/homepage.jsp"><img
						src="<%=request.getContextPath()%>/img/backstage-img/house.svg"
						alt="">
						<p>首頁公告</p></a>
				</div>

				<div class="worker_management">
					<a
						href="<%=request.getContextPath()%>/backstage/worker_management.jsp"><img
						src="<%=request.getContextPath()%>/img/backstage-img/member.svg"
						alt="">
						<p>人員管理</p></a>
				</div>

				<div class="worker_management_list none">
					<a href=""><p>管理員列表</p></a>
				</div>

				<div class="report_list">
					<a href="<%=request.getContextPath()%>/backstage/report.jsp"><img
						src="<%=request.getContextPath()%>/img/backstage-img/list.svg"
						alt="">
						<p>檢舉列表</p></a>
				</div>

				<div class="report_list_all none">
					<a href=""><p>檢舉清單</p></a> <a href=""><p>待審核名單</p></a>
				</div>

				<div class="event_management">
					<a
						href="<%=request.getContextPath()%>/backstage/event_management.jsp"><img
						src="<%=request.getContextPath()%>/img/backstage-img/events.svg">
						<p>活動管理</p></a>
				</div>


				<div class="member_management">
					<a
						href="<%=request.getContextPath()%>/backstage/member_management.jsp"><img
						src="<%=request.getContextPath()%>/img/backstage-img/people.svg"
						alt="">
						<p>會員管理</p></a>
				</div>
				<div class="member_management">
					<a
						href="<%=request.getContextPath()%>/exhibition/BasicExhibition.jsp"><img
						src="<%=request.getContextPath()%>/img/backstage-img/exhibition.svg"
						alt="" />
						<p>展覽管理</p> </a>
				</div>
				<div class="member_management">
					<a href="<%=request.getContextPath()%>/map/MapManagement.jsp"><img
						src="<%=request.getContextPath()%>/img/backstage-img/map.svg"
						alt="">
						<p>地圖管理</p></a>
				</div>

				<div>
					<form action="<%=request.getContextPath()%>/Logout">
						<button type="submit" class="logout">登出</button>
					</form>
				</div>
			</div>


			<div class="panel-text">
				<header class="header">
					<div class="h1">
						<p></p>
					</div>
					<div>
						<a href=""><img class="logo"
							src="<%=request.getContextPath()%>/img/backstage-img/APE3.svg"
							alt="" /></a>
					</div>
				</header>
				<div class="line"></div>

				<div class="body_content_data">
					<div class="container">
						<h2>活動管理</h2>
						<select>
							<option value="a0" selected>待審核</option>
							<option value="a1">通過</option>
							<option value="a2">未通過</option>
							<option value="a3">編輯中</option>
						</select>


						<div class="over">
							<ul class="responsive-table">
								<li class="table-header">
									<div class="header-1">活動名稱</div>
									<div class="header-2">活動日期</div>
									<div class="header-3">活動類型</div>
									<div class="header-4">活動簡介</div>
									<div class="header-5">活動示意</div>
									<div class="header-6">審核</div>
								</li>

								<jsp:useBean id="acttypeDAO" scope="page"
									class="com.activitytype.model.ActivitytypeJDBCDAO" />

								<c:forEach var="activityVO" items="${listA0}">
									<li class="table-row a0" id="a0">
										<div class="col col-1" data-label="ACTIVITY_NAME">${activityVO.activityName}</div>
										<div class="col col-2" data-label="ACTIVITY_DATE">${activityVO.startDate}
											${activityVO.closeDate}</div>
										<div class="col col-3" data-label="ACT_TYPE_NAME">
											<c:forEach var="acttypeVO" items="${acttypeDAO.all}">
												<c:if
													test="${(activityVO.activityTypeNo==acttypeVO.activityTypeNo)}">${acttypeVO.activityTypeName}
												</c:if>
											</c:forEach>
										</div>
										<div class="col col-4" data-label="INTRODUCTION">${activityVO.introduction}</div>
										<div class="col col-5" data-label="ACTIVITY_PIC">
											<img
												src="<%=request.getContextPath()%>/ActPicReader?activityNo1=${activityVO.activityNo}"
												alt="">
										</div>
										<div class="col col-6" data-label="STATUS">
											<span class="STATUS">待審核</span>
										</div>
										<form action="<%=request.getContextPath()%>/EventManagement"
											method="GET">
											<input type="hidden" name="activityNo"
												value="${activityVO.activityNo}">
										</form>
									</li>
								</c:forEach>



								<c:forEach var="activityVO" items="${listA1}">
									<li class="table-row a1" id="a1">
										<div class="col col-1 " data-label="ACTIVITY_NAME">${activityVO.activityName}</div>
										<div class="col col-2 " data-label="ACTIVITY_DATE">${activityVO.startDate}
											${activityVO.closeDate}</div>
										<div class="col col-3 " data-label="ACT_TYPE_NAME">
											<c:forEach var="acttypeVO" items="${acttypeDAO.all}">
												<c:if
													test="${(activityVO.activityTypeNo==acttypeVO.activityTypeNo)}">${acttypeVO.activityTypeName}
												</c:if>
											</c:forEach>

										</div>
										<div class="col col-4 " data-label="INTRODUCTION">${activityVO.introduction}</div>
										<div class="col col-5 " data-label="ACTIVITY_PIC">
											<img
												src="<%=request.getContextPath()%>/ActPicReader?activityNo1=${activityVO.activityNo}"
												alt="">
										</div>
										<div class="col col-6 " data-label="STATUS">
											<span class="STATUS">通過</span>
										</div>
									</li>
								</c:forEach>


								<c:forEach var="activityVO" items="${listA2}">
									<li class="table-row a2" id="a2">
										<div class="col col-1 " data-label="ACTIVITY_NAME">${activityVO.activityName}</div>
										<div class="col col-2 " data-label="ACTIVITY_DATE">${activityVO.startDate}
											${activityVO.closeDate}</div>
										<div class="col col-3 " data-label="ACT_TYPE_NAME">
											<c:forEach var="acttypeVO" items="${acttypeDAO.all}">
												<c:if
													test="${(activityVO.activityTypeNo==acttypeVO.activityTypeNo)}">${acttypeVO.activityTypeName}
												</c:if>
											</c:forEach>
										</div>
										<div class="col col-4 " data-label="INTRODUCTION">${activityVO.introduction}</div>
										<div class="col col-5 " data-label="ACTIVITY_PIC">
											<img
												src="<%=request.getContextPath()%>/ActPicReader?activityNo1=${activityVO.activityNo}"
												alt="">
										</div>
										<div class="col col-6 " data-label="STATUS">
											<span class="STATUS">未通過</span>
										</div>
									</li>
								</c:forEach>
								<c:forEach var="activityVO" items="${listA3}">
									<li class="table-row a3" id="a3">
										<div class="col col-1 " data-label="ACTIVITY_NAME">${activityVO.activityName}</div>
										<div class="col col-2 " data-label="ACTIVITY_DATE">${activityVO.startDate}
											${activityVO.closeDate}</div>
										<div class="col col-3 " data-label="ACT_TYPE_NAME">
											<c:forEach var="acttypeVO" items="${acttypeDAO.all}">
												<c:if
													test="${(activityVO.activityTypeNo==acttypeVO.activityTypeNo)}">${acttypeVO.activityTypeName}
												</c:if>
											</c:forEach>


										</div>
										<div class="col col-4 " data-label="INTRODUCTION">${activityVO.introduction}</div>
										<div class="col col-5 " data-label="ACTIVITY_PIC">
											<img
												src="<%=request.getContextPath()%>/ActPicReader?activityNo1=${activityVO.activityNo}"
												alt="">
										</div>
										<div class="col col-6 " data-label="STATUS">
											<span class="STATUS">編輯中</span>
										</div>
									</li>
								</c:forEach>

							</ul>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="block"></div>

	<script
		src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
	<script
		src="<%=request.getContextPath()%>/js/backstage-js/events_management.js"></script>
</body>
</html>

WebContent/backstage/event_management1.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ page import="com.manager.model.*"%>
<%@ page import="java.util.*"%>
<%@ page import="java.text.*"%>
<%@ page import="com.activity.model.*"%>
<%@ page import="java.util.stream.Collectors"%>
<%@ page import="java.lang.*"%>

<%
	if (session.getAttribute("manager") == null) {
		RequestDispatcher dispatcher = request.getRequestDispatcher("/backstage/login.jsp");
		dispatcher.forward(request, response);
	}
%>


<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link
	href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap"
	rel="stylesheet" />
<link rel="stylesheet"
	href="<%=request.getContextPath()%>/css/backstage-css/basic.css" />
<link rel="stylesheet"
	href="<%=request.getContextPath()%>/css/backstage-css/backendmanagercheack2.css">
<title>活動管理</title>
</head>
<body>
	<div class="block1"></div>
	<div class="bg">
		<img src="<%=request.getContextPath()%>/img/backstage-img/bg.png"
			alt="">
	</div>
	<div class="main">
		<div class="main-div">
			<div class="panel-div">
				<!-- 姓名圖片 -->
				<div class="name">
					<img src="<%=request.getContextPath()%>/PicReader" alt="" />
					<p>${manager.nickname}</p>
				</div>

				<!-- 功能版面 -->
				<!-- 首頁公告 -->
				<div class="homepage">
					<a href="<%=request.getContextPath()%>/backstage/homepage.jsp">
						<img
						src="<%=request.getContextPath()%>/img/backstage-img/house.svg"
						alt="">
						<p>首頁公告</p>
					</a>
				</div>

				<!-- 人員管理 -->
				<div class="worker_management">
					<a
						href="<%=request.getContextPath()%>/backstage/worker_management.jsp">
						<img
						src="<%=request.getContextPath()%>/img/backstage-img/member.svg"
						alt="">
						<p>人員管理</p>
					</a>
				</div>
				<!-- 管理員列表 -->
				<div class="worker_management_list none">
					<a href="">
						<p>管理員列表</p>
					</a>
				</div>

				<!-- 檢舉列表 -->
				<div class="report_list">
					<a href="<%=request.getContextPath()%>/backstage/report.jsp"> <img
						src="<%=request.getContextPath()%>/img/backstage-img/list.svg"
						alt="">
						<p>檢舉列表</p>
					</a>
				</div>
				<!-- 檢舉清單  待審核名單 -->
				<div class="report_list_all none">
					<a href="">
						<p>檢舉清單</p>
					</a> <a href="">
						<p>待審核名單</p>
					</a>
				</div>
				<!-- 活動管理 -->
				<div class="event_management">
					<a
						href="<%=request.getContextPath()%>/backstage/event_management.jsp">
						<img
						src="<%=request.getContextPath()%>/img/backstage-img/events.svg"
						alt="">
						<p>活動管理</p>
					</a>
				</div>

				<!-- 會員管理 -->
				<div class="member_management">
					<a
						href="<%=request.getContextPath()%>/backstage/member_management.jsp">
						<img
						src="<%=request.getContextPath()%>/img/backstage-img/people.svg"
						alt="">
						<p>會員管理</p>
					</a>
				</div>

				<div class="member_management">
					<a
						href="<%=request.getContextPath()%>/exhibition/BasicExhibition.jsp"><img
						src="<%=request.getContextPath()%>/img/backstage-img/exhibition.svg"
						alt="" />
						<p>展覽管理</p> </a>
				</div>
				<div class="member_management">
					<a href="<%=request.getContextPath()%>/map/MapManagement.jsp"><img
						src="<%=request.getContextPath()%>/img/backstage-img/map.svg"
						alt="">
						<p>地圖管理</p></a>
				</div>
				<div>
					<form action="<%=request.getContextPath()%>/Logout">
						<button type="submit" class="logout">登出</button>
					</form>
				</div>
			</div>

			<!-- 內容板塊 -->
			<div class="panel-text">

				<div class="body_content_data">
					<div class="container">
						<h2>活動審核</h2>
						<table class="TB_COLLAPSE">

							<tr class="">
								<th>項目</th>
								<th>明細</th>
							</tr>
							<tr>
								<td>活動編號</td>
								<td>${activityVO.activityNo}</td>
							</tr>
							<tr>
								<td>活動名稱</td>
								<td>${activityVO.activityName}</td>
							</tr>
							<tr>
								<td>活動開始日期</td>
								<td>${activityVO.startDate}</td>
							</tr>
							<tr>
								<td>活動結束日期</td>
								<td>${activityVO.closeDate}</td>
							</tr>
							<tr>
								<td>活動天數</td>
								<td>${activityVO.dayCount}</td>
							</tr>
							<tr>
								<td>活動時間</td>
								<td>${activityVO.activityHours}</td>
							</tr>
							<tr>
								<td>攤位數量</td>
								<td>${activityVO.rentCount}</td>
							</tr>
							<tr>
								<td>建立時間</td>
								<td>${activityVO.createDate}</td>
							</tr>
							<tr>
								<td>活動地址</td>
								<td>${activityVO.address}</td>
							</tr>
							<tr>
								<td>出租價格</td>
								<td>${activityVO.price}</td>
							</tr>
							<tr>
								<td>活動簡介</td>
								<td>${activityVO.introduction}</td>
							</tr>
							<tr>
								<td>活動圖片</td>
								<td><img
									src="<%=request.getContextPath()%>/ActPicReader?activityNo1=${activityVO.activityNo}">
								</td>
							</tr>
							<tr>
								<td>活動類型</td>
								<td>小農商品</td>
							</tr>

							<tr>
								<td>審核狀態</td>
								<td>待審核</td>
							</tr>

						</table>


						<form action="<%=request.getContextPath()%>/EventVerify"
							method="post">
							<button type="submit" class="button1" name="verify" value="pass">通過</button>
							<button type="submit" class="button1" name="verify" value="fail">未通過</button>
						</form>





					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="block"></div>
	<script
		src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

</body>

</html>

WebContent/backstage/homepage.jsp
<%@ page language="java" contentType="text/html ; charset=UTF-8;"
	pageEncoding="UTF-8"%>
<%@ page import="com.manager_msg.model.*"%>
<%@ page import="com.manager.model.*"%>
<%@ page import="java.util.*"%>
<%@ page import="java.text.*"%>

<%
	response.setHeader("Pragma", "no-cache");
	response.setHeader("Cache-Control", "no-cache");
	response.setDateHeader("Expires", -1);
%>

<%
	if (session.getAttribute("manager") == null) {
		RequestDispatcher dispatcher = request.getRequestDispatcher("/backstage/login.jsp");
		dispatcher.forward(request, response);
	}

	Manager_msgJNDIDAO dao = new Manager_msgJNDIDAO();
	List<Manager_msgVO> list = dao.getAll();
	pageContext.setAttribute("list", list);
	ManagerVO managerVO = (ManagerVO) session.getAttribute("manager");
%>


<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<!-- <meta http-equiv="X-UA-Compatible" content="IE=edge" /> -->
<!-- <meta name="viewport" content="width=device-width, initial-scale=1.0" /> -->
<META HTTP-EQUIV="pragma" CONTENT="no-cache">
<META HTTP-EQUIV="Cache-Control" CONTENT="no-store">
<META HTTP-EQUIV="expires" CONTENT="0">
<link rel="stylesheet"
	href="<%=request.getContextPath()%>/css/backstage-css/basic.css" />
<link rel="stylesheet"
	href="<%=request.getContextPath()%>/css/backstage-css/homepage.css">
<link
	href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap"
	rel="stylesheet" />
<title>首頁公告</title>
</head>
<body>

	<div class="block1"></div>
	<div class="bg">
		<img src="<%=request.getContextPath()%>/img/backstage-img/bg.png">
	</div>
	<div class="main">

		<div class="main-div">
			<div class="panel-div">
				<!-- 姓名圖片 -->
				<div class="name">
					<img src="<%=request.getContextPath()%>/PicReader" />
					<p><%=managerVO.getNickname()%></p>
				</div>

				<!-- 功能版面 -->

				<!-- 首頁公告 -->
				<div class="homepage">
					<a href="#"><img
						src="<%=request.getContextPath()%>/img/backstage-img/house.svg"
						alt="">
						<p>首頁公告</p></a>
				</div>

				<!-- 人員管理 -->
				<div class="worker_management">
					<a
						href="<%=request.getContextPath()%>/backstage/worker_management.jsp"><img
						src="<%=request.getContextPath()%>/img/backstage-img/member.svg"
						alt="">
						<p>人員管理</p></a>
				</div>
				<!-- 管理員列表 -->
				<div class="worker_management_list none">
					<a href=""><p>管理員列表</p></a>
				</div>


				<!-- 檢舉列表 -->
				<div class="report_list">
					<a href="<%=request.getContextPath()%>/backstage/report.jsp"><img
						src="<%=request.getContextPath()%>/img/backstage-img/list.svg"
						alt="">
						<p>檢舉列表</p></a>
				</div>
				<!-- 檢舉清單  待審核名單 -->
				<div class="report_list_all none">
					<a href=""><p>檢舉清單</p></a> <a href=""><p>待審核名單</p></a>
				</div>
				<!-- 活動管理 -->
				<div class="event_management">
					<a
						href="<%=request.getContextPath()%>/backstage/event_management.jsp"><img
						src="<%=request.getContextPath()%>/img/backstage-img/events.svg"
						alt="">
						<p>活動管理</p></a>
				</div>

				<!-- 會員管理 -->
				<div class="member_management">
					<a
						href="<%=request.getContextPath()%>/backstage/member_management.jsp"><img
						src="<%=request.getContextPath()%>/img/backstage-img/people.svg"
						alt="">
						<p>會員管理</p></a>
				</div>
				<div class="member_management">
					<a href="<%=request.getContextPath()%>/exhibition/BasicExhibition.jsp"><img
						src="<%=request.getContextPath()%>/img/backstage-img/exhibition.svg"
						alt="" />
						<p>展覽管理</p> </a>
				</div>
					<div class="member_management">
					<a href="<%=request.getContextPath()%>/map/MapManagement.jsp"><img
						src="<%=request.getContextPath()%>/img/backstage-img/map.svg"
						alt="">
						<p>地圖管理</p></a>
				</div>

				<div>
					<form action="<%=request.getContextPath()%>/Logout">
						<button type="submit" class="logout">登出</button>
					</form>
				</div>

			</div>

			<!-- 內容板塊 -->
			<div class="panel-text">
				<header class="header">
					<div class="h1">
						<p>
							歡迎回來,<%=managerVO.getNickname()%></p>
					</div>
					<div>
						<a href=""><img class="logo"
							src="<%=request.getContextPath()%>/img/backstage-img/APE3.svg"
							alt="" /></a>
					</div>
				</header>
				<div class="line"></div>
				<div class="message_board">
					<table>
						<tr class="table_head">
							<th class="name">姓名</th>
							<th class="content">內容</th>
							<th class="time">建立時間</th>
						</tr>

						<%
							for (Manager_msgVO msgVO : list) {
								DateFormat sdf = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
						%>
						<tr class="table_content">
							<td><%=msgVO.getManagerVO().getNickname()%></td>
							<td><%=msgVO.getWork_record()%></td>
							<td><%=sdf.format(msgVO.getEstablished_time())%></td>
						</tr>
						<%
							}
						%>

					</table>
				</div>
				<div class="text_area">
					<textarea name="" id="" cols="44" rows="4"
						placeholder="紀錄一下你今天做了甚麼吧!"></textarea>
				</div>
				<div class="text_button">
					<button type="button">新增</button>
				</div>

			</div>
		</div>
	</div>
	<div class="block"></div>
	<script
		src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
	<script src="<%=request.getContextPath()%>/js/backstage-js/homepage.js"></script>

</body>
</html>

WebContent/backstage/login.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>登入頁面</title>

<link href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap" rel="stylesheet">
<link rel="stylesheet" href="<%=request.getContextPath()%>/css/backstage-css/login.css" />
</head>
<body>
    <div class="main">
      <div class="loginpage">
        <div class="login_content">
          <div class="title">
            <img src="<%=request.getContextPath()%>/img/backstage-img/APE3.svg" alt="" />
            <p>艾普藝森</p>
          </div>
          <div>
            <p>管理員登入</p>
          </div>

          <div class="loginsection">
            <form action="login" method="post">
              <div>
                <label for="account">帳號:</label>
                <input id="account" type="text" pl
                aceholder="請輸入帳號" name="account"/>
              </div>
              <div class="on" id="account_alert">
                <svg
                  fill="currentColor"

                  height="16px"
                  viewBox="0 0 24 24"
                  xmlns="https://www.w3.org/2000/svg"
                >
                  <path
                    d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"
                  ></path>
                </svg>
                <p>請輸入您的帳號</p>
              </div>

              <div>
                <label for="password">密碼:</label>
                <input id="password" type="password" placeholder="請輸入密碼"  name="password"/>
              </div>
              <div class="on" id="password_alert">
                <svg
                  fill="currentColor"
                  width="16px"
                  height="16px"
                  viewBox="0 0 24 24"
                  xmlns="https://www.w3.org/2000/svg"
                >
                  <path
                    d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"
                  ></path>
                </svg>
                <p>請輸入您的密碼</p>
              </div>
              <button type="button" >登入</button>
            </form>
          </div>
        </div>
      </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="<%=request.getContextPath()%>/js/backstage-js/login.js"></script>
  </body>
</html>